MSG_ERROR_INVALID_CELL = "Invalid cell for a cat or the mouse"
MSG_ERROR_GAMESTATUS = "Game status not valid"
MSG_ERROR_MOVE = "Move not allowed"
MSG_ERROR_NEW_COUNTER = "Insert not allowed"
ERROR_MESSAGE_ID = "msg_error"
GAME_SELECTED_SESSION_ID = "game_id"
ERROR_NOT_FOUND = "Page not found"
