# Generated by Django 2.1.5 on 2019-11-09 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.IntegerField(default=0)),
                ('cat2', models.IntegerField(default=2)),
                ('cat3', models.IntegerField(default=4)),
                ('cat4', models.IntegerField(default=6)),
                ('mouse', models.IntegerField(default=59)),
                ('cat_turn', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('target', models.IntegerField()),
                ('date', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='cat_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='datamodel.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.User'),
        ),
    ]
