# Generated by Django 2.1.5 on 2019-11-09 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20191109_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
