# Generated by Django 2.1.5 on 2019-11-09 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20191109_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mouseUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamemouseUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
