# Generated by Django 2.1.5 on 2019-11-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_auto_20191109_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='mouseUser',
            new_name='mouse_user',
        ),
    ]
